<?php

namespace EBM\KMBundle\Repository;

/**
 * CompetenceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceUserRepository extends \Doctrine\ORM\EntityRepository
{
}
