<?php

namespace EBM\KMBundle\Repository;


/**
 * CompetenceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCompetenceUserWithUpvotes($user) {
        $qb = $this
            ->createQueryBuilder('co')
            ->where('co.user = :userid', $user->id())
            ->getQuery();

        return $qb->getResult();
    }
}
