<?php

namespace EBM\KMBundle\Repository;

/**
 * DocumentRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
