<?php

namespace EBM\KMBundle\Repository;

/**
 * EvaluationDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
