<?php

namespace EBM\KMBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Return all tags from a given type.
     *
     * @param $type
     * @return array
     */
    public function getTagsByType($type) {
        $qb = $this
            ->createQueryBuilder('t')
            ->where('t.type = :type')
            ->setParameter('type', $type)
            ->getQuery()
            ;

        return $qb->getResult();
    }
}
