<?php

namespace EBM\MaterielBundle\Repository;

/**
 * CasierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasierRepository extends \Doctrine\ORM\EntityRepository
{
}
