<?php

namespace EBM\MaterielBundle\Repository;

/**
 * CommandeMaterielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeMaterielRepository extends \Doctrine\ORM\EntityRepository
{
}
