<?php

namespace EBM\MaterielBundle\Repository;

/**
 * MaterielTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterielTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
