<?php

namespace EBM\MaterielBundle\Repository;

/**
 * ReservationCasierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationCasierRepository extends \Doctrine\ORM\EntityRepository
{
}
