<?php

namespace EBM\MaterielBundle\Repository;

/**
 * ReservationMachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationMachineRepository extends \Doctrine\ORM\EntityRepository
{
}
