imports:
    - { resource: config_dev.yml }
    - { resource: parameters_staging.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# ElasticSearch
fos_elastica:
    clients:
        default: { host: fablab_elastic, port: 9200 }
    indexes:
        fablab:
            types:
                post:
                    properties:
                        content: ~
                        author: ~
                    persistence:
                        driver: orm
                        model: EBM\KMBundle\Entity\Post
                        provider: ~
                        finder: ~
                tags:
                    properties:
                        name: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: EBM\KMBundle\Entity\Tag
                        provider: ~
                        finder: ~
                ressources:
                    properties:
                        name: ~
                        description: ~
                    persistence:
                        driver: orm
                        model: EBM\KMBundle\Entity\Document
                        provider: ~
                        finder: ~