# http://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration

parameters:
    database_host: fablab_db
    database_port: ~
    database_name: filrouge
    database_user: filrouge
    database_password: filrouge
