services:
#    core_user.example:
#        class: Core\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    form.registration:
        class: Core\UserBundle\Form\RegistrationFormType
        tags:
            - { name: "form.type", alias: "user_registration" }
    core_user.service.role:
        class: Core\UserBundle\Utilities\RoleService
        arguments: ["@security.role_hierarchy"]