<?php

namespace EBM\SocialNetworkBundle\Repository;

/**
 * ProjectSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
