<?php

namespace EBM\SocialNetworkBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationRepository extends EntityRepository
{
    public function getPublicationWithSubscriptions(array $tagsNames, array $projectNames)
    {

        if ((!is_array($tagsNames) || empty($tagsNames)) && (!is_array($projectNames) || empty($projectNames))) {
            return [];
        }

        if (!is_array($projectNames) || empty($projectNames)){
            $qb = $this->createQueryBuilder('pub');
            // On fait une jointure avec l'entité Category avec pour alias « c »
            $qb
                ->innerJoin('pub.tags', 'tag')
                ->addSelect('tag')
            ;
            // Puis on filtre sur le nom des catégories à l'aide d'un IN
            $qb->where($qb->expr()->in('tag.name', $tagsNames));
            // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

            // Enfin, on retourne le résultat
            return $qb
                ->getQuery()
                ->getResult()
                ;
        }

        if (!is_array($tagsNames) || empty($tagsNames)){
            $qb = $this->createQueryBuilder('pub');
            // On fait une jointure avec l'entité Category avec pour alias « c »
            $qb
                ->innerJoin('pub.projects', 'pro')
                ->addSelect('pro')
            ;
            // Puis on filtre sur le nom des catégories à l'aide d'un IN
            $qb->where($qb->expr()->in('pro.name', $projectNames));
            // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

            // Enfin, on retourne le résultat
            return $qb
                ->getQuery()
                ->getResult()
                ;
        }

        $qb = $this->createQueryBuilder('pub');
        // On fait une jointure avec l'entité Category avec pour alias « c »
        $qb
            ->innerJoin('pub.projects', 'pro')
            ->innerJoin('pub.tags', 'tag')
            ->addSelect('pro')
            ->addSelect('tag');

            $qb->where($qb->expr()->in('pro.name', $projectNames));
        ;
    }
}
