ebm_social_network_homepage:
    path:     /
    defaults:
        _controller: EBMSocialNetworkBundle:Default:index

ebm_social_network_view:
    path:     /{id}
    defaults:
        _controller: EBMSocialNetworkBundle:Publication:view
    requirements:
        id: \d+

ebm_social_network_add:
    path:     /add
    defaults:
        _controller: EBMSocialNetworkBundle:Publication:add

ebm_social_network_edit:
    path:     /edit/{id}
    defaults:
        _controller: EBMSocialNetworkBundle:Publication:edit
    requirements:
        id: \d+

ebm_social_network_delete:
    path:     /delete/{id}
    defaults:
        _controller: EBMSocialNetworkBundle:Publication:delete
    requirements:
        id: \d+

ebm_social_network_subscriptions:
    path:     /subscriptions
    defaults:
        _controller: EBMSocialNetworkBundle:Subscriptions:index

ebm_social_publication_comment_add:
    path:     /{id}/comment/add/
    defaults:
        _controller: EBMSocialNetworkBundle:Comment:add
    requirements:
        id: \d+
