<?php

namespace EBM\GDPBundle\Repository;

/**
 * DocumentTypeProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentTypeProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
