<?php

namespace EBM\GDPBundle\Repository;

/**
 * DocumentProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
