services:
    cp_iconbar.twig.extension:
        class: Core\IconbarBundle\Twig\Extension\commonExtension
        public: false
        tags:
            - { name: twig.extension }
    cp_iconbar.twig.global:
        class: Core\IconbarBundle\Listener\TwigConstructorListener
        arguments: ["@twig"]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest