ebm_materiel_homepage:
    path:     /
    defaults: { _controller: EBMMaterielBundle:Machine:index }

ebm_materiel_machines:
    path:     /machines
    defaults: { _controller: EBMMaterielBundle:Machine:machine }

ebm_materiel_machines_selection:
    path:     /machines/selection
    defaults: { _controller: EBMMaterielBundle:Machine:selectionMachine }

ebm_materiel_machines_planning:
    path:     /machines/planning/{machine}
    defaults:
        _controller: EBMMaterielBundle:Machine:planningMachine
        machine: none

ebm_materiel_machines_reservation:
    path:     /machines/reservation/{debut}/{fin}
    defaults:
        _controller: EBMMaterielBundle:Machine:reservationMachine
        debut:
        fin:
