ebm_materiel_homepage:
    path:     /
    defaults: { _controller: EBMMaterielBundle:Machine:index }

ebm_materiel_machines:
    path:     /machines
    defaults: { _controller: EBMMaterielBundle:Machine:machine }

ebm_materiel_machines_planning:
    path:     /machines/planning
    defaults: { _controller: EBMMaterielBundle:Machine:planningMachine }

ebm_materiel_machines_reservation:
    path:     /machines/reservation/{debut}/{fin}
    defaults:
        _controller: EBMMaterielBundle:Machine:reservationMachine
        debut:
        fin: