ebm_materiel_homepage:
    path:     /
    defaults: { _controller: EBMMaterielBundle:Machine:index }

ebm_materiel_machines:
    path:     /machines
    defaults: { _controller: EBMMaterielBundle:Machine:machine }

ebm_materiel_machines_selection:
    path:     /machines/selection
    defaults: { _controller: EBMMaterielBundle:Machine:selectionMachine }

ebm_materiel_machines_planning:
    path:     /machines/planning/{machineId}
    defaults:
        _controller: EBMMaterielBundle:Machine:planningMachine
        machineId: 1

ebm_materiel_machines_reservation:
    path:     /machines/reservation/{machine}/{debut}/{fin}
    defaults:
        _controller: EBMMaterielBundle:Machine:reservationMachine
        machine: 1
        debut: "2017-01-01T08:00:00"
        fin:

ebm_materiel_machines_ajout:
    path:     /machines/ajout
    defaults:
        _controller: EBMMaterielBundle:Machine:ajoutMachine

ebm_materiel_machines_ajoutee:
    path: /machines/added
    defaults:
        _controller: EBMMaterielBundle:Machine:machineAdded

ebm_materiel_machines_reservation_submit:
    path: /test/post
    defaults:
        _controller: EBMMaterielBundle:Machine:reservationSubmit

ebm_materiel_machine_affiche_reservation:
    path:    /machines/affiche
    defaults:
        _controller: EBMMaterielBundle:Machine:reservationAffiche

